config/routes.rb
Rails.application.routes.draw do

  get "/", to: redirect("/volun")

  scope "volun" do
    mount Ckeditor::Engine => '/ckeditor'
    concern :downloadable do
      get 'download', on: :member
    end
    resources :new_campaings 

    namespace :rt do
      resources :others, only:[:new,:create]
      resources :activity_unpublishings, only:[:new,:create], param: :activity_id
      resources :activity_publishings, only:[:new,:create]
      resources :project_unpublishings, only:[:new,:create], param: :project_id
      resources :project_publishings, only:[:new,:create], param: :project_id
      resources :volunteers_demands, only:[:new,:create], param: :project_id
      resources :entity_unsubscribes, only:[:new,:create]
      resources :volunteer_appointments, only:[:new,:create]
      resources :volunteer_amendments, only:[:new,:create]
      resources :volunteer_unsubscribes, only:[:new,:create], param: :project_id
      resources :volunteer_subscribes, only:[:new,:create,:index]
      resources :volunteer_project_subscribes, only:[:new,:create,:index]
      resources :solidarity_chains, only:[:new,:create]
    end

    resources :addresses do
      get 'bdc_search_towns', on: :collection
      get 'bdc_search_roads', on: :collection
      get 'bdc_search_road_numbers', on: :collection
    end

    resources :activities, only: [:show, :index ] do
      collection do
        get :my_area
        get :boroughs
        get :search
      end
    end

    resources :entities, only:[:show,:new,:create] do
      resources :projects, only:[:index, :show], param: :q
      resources :activities, only:[:index, :show], param: :q
    end

    resources :projects, only: [:show, :index] do
      collection do
        get :my_area
        get :boroughs
        get :search
      end
      resources :images
      resources :links
    end

    resources :links, concerns: :downloadable

    # resources :volunteers do
    #   resources :projects, only:[:index], param: :q
    # end

    devise_for :users, controllers: {
                        sessions: 'users/sessions',
                        passwords: 'users/passwords',
                        registrations: 'users/registrations'
                      }
    resources :users, only: [:show] do
      collection do
        get :search_activities
        get :search_projects
        get :search_requests
        get :search_meetings
        post :download_zip
      end
    end

    get 'text_json' => 'welcome#test'

    get 'welcome/index'
    get '/whoami' => 'pages#whoami'
    get '/accesibility' => 'pages#accesibility'
    get '/volunteers' => 'pages#volunteers'
    get '/entities' => 'pages#entities'
    get '/mailchimp' => 'pages#mailchimp'
    get '/conditions' => 'pages#conditions'
    get '/blog' => redirect("https://voluntariospormadridblog.madrid.es/")
    get '/mta_privacy' => 'pages#mta_privacy'

    get '/apple-app-site-association', to: redirect('/system/apple-app-site-association')
    get '/.well-known/apple-app-site-association', to: redirect('/system/apple-app-site-association')
    resources :pages, path: '/', only: [:show]

    root 'welcome#index'
    post "/" => "welcome#index"

    draw :ws
    draw :profile
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_addressBDC.html.erb
<%= javascript_pack_tag 'address' %>
<div class="js-address">
  <div class="address-fields col-md-12">
    <div class="row row-4-1">
      <% normalize = f.object.normalize %>
      <%= f.check_box :normalize, class: 'js-normalize'  %>
    </div>
  </div>
  <div class="address-fields col-md-12">
    <fieldset>
      <div class="form-group">
        <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:country) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:country) %>"><%= Rt::EntitySubscribe.human_attribute_name(:country) %> <span class="asterisco">*</span></label>
        <%= f.text_field :country, as: :string,  value: ("ESPAÑA" ), readonly: true, class: 'js-country'%>
      </div>
      <div class="form-group">
        <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:province) %>"><%= Rt::EntitySubscribe.human_attribute_name(:province) %> <span class="asterisco">*</span></label>
        <%= f.select :province, provinces_select_options, {include_blank: "", selected: "MADRID"},  class: 'js-province' %>
      </div>
      <div class="form-group">
        <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:town) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:town) %>"><%= Rt::EntitySubscribe.human_attribute_name(:town) %> <span class="asterisco">*</span></label>
        <%= f.text_field :town, data: { 'js-search-towns-url' => bdc_search_towns_addresses_url }, class: 'js-town' %>
      </div>
    </fieldset>
    <fieldset>
      <div class="form-group">
        <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_type) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_type) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_type) %> <span class="asterisco">*</span></label>
        <%= f.select :road_type, road_types_select_options, {include_blank: "", selected: ""},  class: 'small'  %>
      </div>
      <div class="form-group">
        <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_name) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_name) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_name) %> <span class="asterisco">*</span></label>
        <%= f.text_field :road_name, class: 'js-road_name', data: { 'js-search-road-names-url' => bdc_search_roads_addresses_url } %>
      </div>
      <div class="form-group">
        <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_number_type) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_number_type) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_number_type) %> <span class="asterisco">*</span></label>
        <%= f.text_field :road_number_type, class: 'm-width250 js-road_number_type', readonly: normalize  %>
      </div>
      <div class="form-group">
        <% if !normalize %>
        <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_number) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_number) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_number) %> <span class="asterisco">*</span></label>
        <%= f.text_field :road_number, collection: [f.object.road_number || ''],  class: 'm-width250 js-road_number-select'%>
        <% end %>
      </div>
      <div class="form-group">
        <% if normalize %>
        <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_number) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_number) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_number) %> <span class="asterisco">*</span></label>
        <%= f.text_field :road_number, class: 'm-width250 js-road_number-input', data: { 'js-search-road-numbers-url' => bdc_search_road_numbers_addresses_url }%>
        <% end %>
      </div>
      <div class="form-group">
        <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:postal_code) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:postal_code) %>"><%= Rt::EntitySubscribe.human_attribute_name(:postal_code) %> <span class="asterisco">*</span></label>
        <%= f.text_field :postal_code, class: 'js-postal_code', readonly: normalize, data: { mask: '99999'} , wrapper_html: { class: 'postal_code col-md-3' } %>
      </div>
    </fieldset>
    <div class="form-group">
      <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:grader) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:grader) %>"><%= Rt::EntitySubscribe.human_attribute_name(:grader) %> <span class="asterisco">*</span></label>
      <%= f.text_field :grader, class: 'm-width80 js-grader', readonly: normalize , wrapper_html: { class: 'col-md-3' } %>
    </div>
    <div class="row row-4-3">
      <%= f.text_field :stairs,  class: 'm-width250 js-stairs'  %>
      <%= f.text_field :floor,  class: 'm-width250 js-floor'  %>
      <%= f.text_field :door,  class: 'm-width250 js-door'  %>
    </div>
  </div>
</div>

app/views/shared/_addressInternet.html.erb
<fieldset>
    <legend>
        <div class="row">
            <div class="col-md-9">
                <div class="form-group">
                    <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_type) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_type) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_type) %> <span class="asterisco">*</span></label>
                    <%= f.select :road_type, road_types_select_options, {include_blank: "", selected: f.object.road_type || ""},  {class: 'small', 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:road_type)}  %>
                </div>
                <div class="form-group">
                    <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_name) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_name) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_name) %> <span class="asterisco">*</span></label>
                    <%= f.text_field :road_name, { class: 'big', 'aria-label' =>  Rt::EntitySubscribe.human_attribute_name(:road_name) } %>
                </div>
                <div class="form-group">
                    <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_number_type) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_number_type) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_number_type) %><span class="asterisco">*</span></label>
                    <%= f.select :road_number_type, number_types_select_options, {include_blank: "", selected: f.object.road_number_type || ""},  {class: 'small', 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:road_number_type)} %>
                </div>
                <div class="form-group">
                    <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_number) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_number) %> <span class="asterisco">*</span></label>
                    <%= f.text_field :road_number, { class: 'small', 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:road_number) }  %>
                </div>
                <div class="form-group">
                    <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:postal_code) %>"><%= Rt::EntitySubscribe.human_attribute_name(:postal_code) %><span class="asterisco">*</span></label>
                    <%= f.text_field :postal_code, { class: 'small', 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:postal_code) } %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9">
                <div class="form-group">
                    <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:province) %>"><%= Rt::EntitySubscribe.human_attribute_name(:province) %> <span class="asterisco">*</span></label>
                    <%= f.select :province_id, provinces_select_options, {include_blank: "", selected:f.object.province || ""},  {class: 'medium', 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:province)} %>
                </div>
                <div class="form-group">
                    <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:town) %>"><%= Rt::EntitySubscribe.human_attribute_name(:town) %><span class="asterisco">*</span></label>
                    <%= f.text_field :town, { class: 'medium', 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:town) } %>
                </div>
            </div>
        </div>
    </legend>
</fieldset>

app/views/shared/_addressInternetNT.html.erb
<% if current_user.loggable_type=="Entity" && !(local_assigns.has_key? :rt_volunteers_demand)
    span=""
else 
    span="*" 
end%> 

<fieldset>
    <div class="row">
        <div class="col-md-9"><legend>
            <div class="form-group">
                <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_type) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_type) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_type) %> <span class="asterisco"><%=span%></span></label>
                <%= f.select :road_type, road_types_select_options, {include_blank: "", selected: f.object.road_type || ""},  {class: 'small', 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:road_type)}  %>
            </div>
            <div class="form-group">
                <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_name) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_name) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_name) %> <span class="asterisco"><%=span%></span></label>
                <%= f.text_field :road_name, { class: 'big' , 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:road_name)} %>
            </div>
            <div class="form-group">
                <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:number_type) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:number_type) %>"><%= Rt::EntitySubscribe.human_attribute_name(:number_type) %><span class="asterisco"><%=span%></span></label>
                <%= f.select :number_type, number_types_select_options, {include_blank: "", selected: f.object.number_type || ""}, {class: 'small', 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:number_type)} %>
            </div>
            <div class="form-group">
                <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:road_number) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:road_number) %>"><%= Rt::EntitySubscribe.human_attribute_name(:road_number) %> <span class="asterisco"><%=span%></span></label>
                <%= f.text_field :road_number, { class: 'small' , 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:road_number)}  %>
            </div>
            <div class="form-group">
                <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:postal_code) %>", alt="<%= Rt::EntitySubscribe.human_attribute_name(:postal_code) %>"><%= Rt::EntitySubscribe.human_attribute_name(:postal_code) %><span class="asterisco"><%=span%></span></label>
                <%= f.text_field :postal_code, { class: 'small' , 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:postal_code)} %>
            </div>
            <% if current_user.loggable_type=="Entity" %>
                <div class="form-group">
                    <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:district) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:district) %>"><%= Rt::EntitySubscribe.human_attribute_name(:district) %> </label>
                    <%= f.select :district_id, @hash_district||{},{include_blank: "", selected: f.object.district_id || ""}, {'aria-label' => Rt::EntitySubscribe.human_attribute_name(:district)}%>
                </div>
            <% end%></legend> 
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="form-group">
                <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:province) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:province) %>"><%= Rt::EntitySubscribe.human_attribute_name(:province) %> <span class="asterisco"><%=span%></span></label>
                <%= f.select :province_id, provinces_select_options, {include_blank: ""}, { class: 'medium', 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:province)} %>
            </div>
            <div class="form-group">
                <label class="labelUp" id="<%= Rt::EntitySubscribe.human_attribute_name(:town) %>" alt="<%= Rt::EntitySubscribe.human_attribute_name(:town) %>"><%= Rt::EntitySubscribe.human_attribute_name(:town) %><span class="asterisco"><%=span%></span></label>
                <%= f.text_field :town, { class: 'medium', 'aria-label' => Rt::EntitySubscribe.human_attribute_name(:town)} %>
            </div>
        </div>
    </div>
</fieldset>

app/views/shared/_area.html.erb
<%if !areas.blank?%>
    <% areas.each do |area| %>
        <span class="tag"><i class="fa <%= area.description %>" aria-hidden="true"></i><%= area.name.capitalize %></span>
    <%end%>
<%else%>
    <% areas.each do |area| %>
        <span class="tag"><i class="fa <%= area.description %>" aria-hidden="true"></i><%= area.name.capitalize %></span>
    <%end%>
<%end%>

app/views/shared/_errors.html.erb
<% if model_name.errors.any? %>
  <div class="row">
    <div class="col-md-12">
      <div id="errores" class="nofluid">
        <div>
          <h2 class="title-modal"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>
          <% if model_name.errors.count >1%>
            <span><%=t('shared.errors',num: model_name.errors.count)%></span></h2>
          <% else%>
            <span><%=t('shared.error',num: model_name.errors.count)%></span></h2>
          <%end%>
          <ul>
            <% model_name.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_locale_switcher.html.erb
<% if I18n.available_locales.size > 1 %>
  <div class="locale" id="js-locale" data-current-local="<%= I18n.locale %>">
    <span class="inline-block">
      <%= t("layouts.header.locale") %>
    </span>
    <form class="locale-form">
      <select class="js-location-changer locale-switcher" name="locale-switcher">
        <% I18n.available_locales.map do |loc| %>
          <option <%= "selected" if loc == I18n.locale %>
            value="<%= current_path_with_query_params(locale: loc) %>">
            <%= I18n.t("locale", locale: loc) %>
          </option>
        <% end %>
      </select>
    </form>
  </div>
<% end %>

app/views/shared/_pagination.html.erb
<style>
  .pagination > .active > a, .pagination > .active > span, .pagination > .active > a:hover, .pagination > .active > span:hover, .pagination > .active > a:focus, .pagination > .active > span:focus{
    background: rgba(255, 102, 0, 0.7);
    border-color: #fc4f08;
    color: #1d1d1d;
    }

  .pagination > li > a, .pagination > li > span, .pagination > li > a:hover, .pagination > li > span:hover, .pagination > li > a:focus, .pagination > li > span:focus{
  color: #fc4f08;
    }
</style>
<div class="pagination-container">
  <ul class='list-inline'>
    <li class="pull-left"><%= will_paginate(collection, renderer: BootstrapPagination::Rails, params: local_assigns[:params]) %></li>
  </ul>
</div>

app/views/shared/_participation.html.erb
<div id="participation">
  <% if current_user && current_user.loggable.class=="Entity" %>
    <%= link_to t('volunteer_subscribe.interest'), projects_path(@project.id), class: "event-link " %>
  <% else %>
    <span> <%= t('volunteer_subscribe.participation') %> <%= link_to t('devise_views.sessions.new.submit'), new_user_session_path, alt: t('devise_views.sessions.new.submit') %> o <%= link_to t('volunteer_subscribe.new'), new_rt_volunteer_subscribe_path, alt: t('volunteer_subscribe.new') %></span>
  <% end %>
</div>
<br>

app/views/shared/_personal_area.html.erb
<% if !current_user.blank? %>  
  <li class="areaT">
    <i class="fa fa-user" style="color: #FF6600"></i> <%= link_to t('shared.personal_area'), user_path(current_user.id), alt: t('shared.personal_area') %>
  </li>
<% end %>

app/views/shared/_print.html.erb
<a href="javascript:window.print();" id="print_link" 
    class="button warning tiny radius right event-link" alt="<%= t("shared.print.print_button") %>">
    <%= t("shared.print.print_button") %>
</a>

app/views/shared/_protection.html.erb
<div id="legalWrapper">
  <%if controller_name!='entities'%>    
    <%=@component.try(:content).to_s.html_safe%>
    <h4 style="margin-top: 50px"><%=t('shared.protection.data')%></h4>
    <div class="checkCustom">
      <%= check_box_tag :terms_of_service, {'aria-label' => t('shared.protection.data')} %>
      <label id="<%=t('shared.protection.data')%>" for="terms_of_service"></label>
    </div>
    <span class="labelCheck textCheckbox">
      <%= t("devise_views.users.registrations.new.protection_data_accept").html_safe %>
    </span>
  <%else%>
    <%=@component.try(:content).to_s.html_safe%>
  <%end%>
</div>

app/views/shared/_scroll_infinite.html.erb
<div class="row">
  <div class="col-md-12">
    <% if records.current_page != records.total_pages && records.current_page < records.total_pages %>
    <p id="view-more">
      <%= link_to(t('shared.show_more'), url_for(page: records.current_page + 1), {:remote => true}), alt: t('shared.show_more') %>
    </p>
    <% end%>
  </div>
</div>

app/views/shared/_scroll_infinite_activities.html.erb
<div class="row">
  <div class="col-md-12">
    <% if records.current_page * Kaminari.config.default_per_page < num_records %>
      <p id="view-more">
        <%= link_to(t('shared.show_more'), url_for(page: records.current_page + 1), {:remote => true, alt: t('shared.show_more')}) %>
      </p>
    <% end%>
  </div>
</div>

app/views/shared/popup_image.js.erb
<% template_path =  local_assigns[:template_path] || "#{params[:controller]}/#{params[:action]}" %>
<% html_content  =  j(render file: template_path) %>


$('<div/>', {
  id: 'dialog',
  style: 'display:none; background: white; box-shadow: 0 0 1em grey; width-min:500px;'
  }).appendTo('body').
html("<%= html_content %>").
dialog({
  title:       '',
  draggable:   false,
  resizable:   false,
  closeText:   "X",
  stack:       false,
  classes: {
    "ui-dialog": "highlight"
  },
  dialogClass: "no-close",
  modal:       false,
  width:       500,
 
  buttons: [
    {
      text: "<%= t('action.close') %>",
      class: "btn btn-default",
      click: function() {
         $(this).remove();
       
      }
    }
  ]
});