config/routes.rb
Rails.application.routes.draw do

  get "/", to: redirect("/volun")

  scope "volun" do
    mount Ckeditor::Engine => '/ckeditor'
    concern :downloadable do
      get 'download', on: :member
    end
    resources :new_campaings 

    namespace :rt do
      resources :others, only:[:new,:create]
      resources :activity_unpublishings, only:[:new,:create], param: :activity_id
      resources :activity_publishings, only:[:new,:create]
      resources :project_unpublishings, only:[:new,:create], param: :project_id
      resources :project_publishings, only:[:new,:create], param: :project_id
      resources :volunteers_demands, only:[:new,:create], param: :project_id
      resources :entity_unsubscribes, only:[:new,:create]
      resources :volunteer_appointments, only:[:new,:create]
      resources :volunteer_amendments, only:[:new,:create]
      resources :volunteer_unsubscribes, only:[:new,:create], param: :project_id
      resources :volunteer_subscribes, only:[:new,:create,:index]
      resources :volunteer_project_subscribes, only:[:new,:create,:index]
      resources :solidarity_chains, only:[:new,:create]
    end

    resources :addresses do
      get 'bdc_search_towns', on: :collection
      get 'bdc_search_roads', on: :collection
      get 'bdc_search_road_numbers', on: :collection
    end

    resources :activities, only: [:show, :index ] do
      collection do
        get :my_area
        get :boroughs
        get :search
      end
    end

    resources :entities, only:[:show,:new,:create] do
      resources :projects, only:[:index, :show], param: :q
      resources :activities, only:[:index, :show], param: :q
    end

    resources :projects, only: [:show, :index] do
      collection do
        get :my_area
        get :boroughs
        get :search
      end
      resources :images
      resources :links
    end

    resources :links, concerns: :downloadable

    # resources :volunteers do
    #   resources :projects, only:[:index], param: :q
    # end

    devise_for :users, controllers: {
                        sessions: 'users/sessions',
                        passwords: 'users/passwords',
                        registrations: 'users/registrations'
                      }
    resources :users, only: [:show] do
      collection do
        get :search_activities
        get :search_projects
        get :search_requests
        get :search_meetings
        post :download_zip
      end
    end

    get 'text_json' => 'welcome#test'

    get 'welcome/index'
    get '/whoami' => 'pages#whoami'
    get '/accesibility' => 'pages#accesibility'
    get '/volunteers' => 'pages#volunteers'
    get '/entities' => 'pages#entities'
    get '/mailchimp' => 'pages#mailchimp'
    get '/conditions' => 'pages#conditions'
    get '/blog' => redirect("https://voluntariospormadridblog.madrid.es/")
    get '/mta_privacy' => 'pages#mta_privacy'

    get '/apple-app-site-association', to: redirect('/system/apple-app-site-association')
    get '/.well-known/apple-app-site-association', to: redirect('/system/apple-app-site-association')
    resources :pages, path: '/', only: [:show]

    root 'welcome#index'
    post "/" => "welcome#index"

    draw :ws
    draw :profile
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  respond_to :html, :js, :json
  skip_before_action :verify_authenticity_token

  before_action :load_data_calendar, only: [:index]

  def index
    @participation_projects = ProjectsVolunteer.joins(:project).all.select("projects.subtype_pt as subtype_pt, count(1) as total").group("projects.subtype_pt")
    @areas_percent = AreasProject.joins("INNER JOIN areas ON areas.id = areas_projects.area_id").group("areas.name").count
    Ahoy::Event.create(name: "Visit", properties: {title: "Página principal"}.to_json, user_id: current_user.try(:id), visit_id: current_visit.try(:id), time:Time.now)
    @num_activities = Activity.all.where("EXTRACT(YEAR FROM start_date) = #{Date.today.year} AND EXTRACT(MONTH FROM start_date) = #{Date.today.month}").count
    @projects_featured = Project.includes(:areas).featured
    @project_urgent = Project.urgent.limit(1)
    @locations = Event.includes(:address, :project).where(eventable_type: Project.name).as_json(only: [:id], include: { address: { only: [:latitude, :longitude] }, project: { only: [:id, :pt_extendable_type, :name] }  })
    params[:day] ||= Time.now
    @search_q = Timetable.select('execution_date, activities.id').joins(:activity).order(:execution_date).group('execution_date, activities.id').search(execution_date_gteq: Time.now)
    @events = @search_q.result.limit(2)
    @list_days = Activity.includes(:timetables).distinct.activities_present(Time.now).order('timetables.execution_date').pluck('timetables.execution_date').to_json

    @activities_search = @activities_unpag
      
    @activities = @activities_search.paginate(page: params[:page], per_page: Kaminari.config.default_per_page)

    @components = @component_home.child_components.order(:order)

    respond_to do |format|
      format.html
      format.js
    end
    
  rescue => e
    begin
      Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  

  private

  def load_data_calendar
    @current_date_calendar = Date.today       

    start_date =  @current_date_calendar.beginning_of_month.to_date
    end_date=  @current_date_calendar.end_of_month.to_date
    @activities_unpag = Activity.all.order(start_date: :desc).where("start_date::date between ?::date and ?::date OR end_date::date between ?::date and ?::date OR ?::date between start_date::date and end_date::date OR ?::date between start_date::date and end_date::date ",start_date,end_date,start_date,end_date, start_date,end_date ) 
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_agends.html.erb
<section id="activities" class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h2 class="titlePage"><%=c.title%> <div class="right"><%= link_to t('action.show_activity'), activities_path, class: "event-link negative rightChev", alt: t('action.show_activity') %></div></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="row" style="padding: 0px;overflow-x:auto;">   
        <table class="table table-striped" style="width: 100%">
          <thead><tr><%=get_week_first_monday%></tr></thead>
          <tbody><%=get_days_month_range(@current_date_calendar, @activities_unpag, {})%></tbody>
        </table>
      </div>
      <div class="row">
        <div class="col-12">
          <div style="height: 1rem;width: 1rem; border-radius: 100%;background: rgba(255, 102, 0, 1);float: left;padding: 0.8rem;margin-right: 1rem;"></div> Eventos
        </div>
        <div class="col-12">
          <div style="height: 1rem;width: 1rem; border-radius: 100%;background: #FFA200;float: left;padding: 0.8rem;margin-right: 1rem;"></div> Día actual
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div id="activities">
        <%if @activities_search.count.to_i == 0%>
          <h4><%=t('welcome.not_activity') %></h4>
        <%elsif @activities_search.count.to_i == 1 %>
          <h4><%=t('welcome.next_activity') %></h4>
        <%else%>
          <h4><%=t('welcome.next_activities',num_activities:@activities_search.count) %></h4>
        <%end%>

        <div class="col-md-12" style="margin-top: 1rem">
          
          <div class="row" style="overflow: auto;">
            <% @activities.each do |activity|%>
              <div class="col-12">
                <%=render partial: 'activities/activity', locals: {activity: activity}%>
              </div>
            <%end%>
          </div>      
          <div class ="row">
            <div class="col">
              <%= render partial: "shared/pagination", locals: {collection: @activities} %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_map.html.erb
<section id="mapWrapper" class="container-fluid nopadding">
  <div class="row">
    <h2 class="col-md-12 titlePage" style="text-align:left"><%=c.title%></h2>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div id="map"> </div>
        <% i=0
          Activity.all.each do |activity| 
            activity.addresses.each do |address|
              coords = get_latitude_and_longitude(address)%>
              
            <%= javascript_tag do %>
              <%if !coords.blank?%>
               coords_convert(<%=coords[:latitude]%>,<%=coords[:longitude]%>,"<%=asset_path('project_yellow.png').to_s%>",<%=i%>,{"id":<%=activity.id%>,"name": "<%=activity.name%>"},'activity');
              
              <% i=i+1 %>
              <%end%>
            <% end %>
          <%end%>
        <%end%>
    </div>
  </div>
</section>

<div id="project_urgent">
<% if @project_urgent.size > 0 %>
  <% content_for :head do %>
    <% @project_urgent.each do |project| %>
      <div class="urgenteWrapper">
        <style type="text/css">
            .parpadea { 

                animation-name: parpadeo; 
                animation-duration: 1s; 
                animation-timing-function: linear; 
                animation-iteration-count: infinite; 
              
                -webkit-animation-name:parpadeo; 
                -webkit-animation-duration: 1s; 
                -webkit-animation-timing-function: linear; 
                -webkit-animation-iteration-count: infinite; 
            } 
              
              @-moz-keyframes parpadeo{   
                0% { opacity: 1.0; } 
                50% { opacity: 0.5; } 
                100% { opacity: 1.0; } 
              } 
              
              @-webkit-keyframes parpadeo {   
                0% { opacity: 1.0; } 
                50% { opacity: 0.5; } 
                100% { opacity: 1.0; } 
              } 
              
              @keyframes parpadeo {   
                0% { opacity: 1.0; } 
                50% { opacity: 0.5; } 
                100% { opacity: 1.0; } 
              }
        </style>
          <% if project.urgent %> 
            <p class="parpadea text-left" style="padding: 10px; text-transform:uppercase; background: #ff6600; color: white; font-weight: bold; font-size: 20px;"><%=t('project.urgent')%></p> 
          <%end%>
        <h2><%=  project.name %></h2>
        <p> <%= truncate(strip_tags(project.description), length: 180, :escape => false).html_safe %></p>
        <i><%= link_to  "" , project_path(project), class: "fa fa-chevron-right" %> </i>
      </div>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/welcome/_projects.html.erb
<section id="projects" class="container-fluid">
  <div class="row">
    <div id="projects" class="col-md-12">
      <h2 class="titlePage"><%=c.title%> <div class="right"><%= link_to t('action.show_project'), projects_path, class: "event-link negative rightChev", alt: t('action.show_project') %></div></h2>
      <ul class="row destacadosWrapperHome">
        <%= render partial: 'projects/project', locals: { records: @projects_featured }  %>
      </ul>
    </div>
  </div>
</section>

app/views/welcome/_rrss.html.erb
<section id="rrss">
  <div class="row">
    <h2 class="col-md-12 titlePage" style="text-align:left"><%=c.title%></h2>
  </div>
  <div class="row timelines">
    <label id="timeline_twitter" class="col-md-6">
      <a class="twitter-timeline" data-lang="es" data-width="100%" data-height="400" href="https://twitter.com/voluntmadrid">Tweets de Voluntarios por Madrid</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </label>
    <label id="timeline_facebook"  class="col-md-6">
      <iframe name="facebook" src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fpg%2Fvoluntariospormadrid%2Fposts%2F%3Fref%3Dpage_internal&tabs=timeline&small_header=false&hide_cover=false&show_facepile=true&appId" width="100%" height="400" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
    </label>
  </div>
</section>

app/views/welcome/_statistics.html.erb
<section id="actividadesHome" class="container-fluid">
  <div class="row">
    <h2 class="col-md-12 titlePage" style="text-align:left"><%=c.title%></h2>
  </div>
  <div class="row" style="margin-bottom: 20px">
    <h3 class="col-md-2 text-center"><%=t('welcome.volunteers_active')%></h3>
    <h3 class="col-md-2 text-center"><%=t('welcome.projects_active')%></h3>
    <h3 class="col-md-3 text-center"><%=t('welcome.participation_percent')%></h3>
    <h3 class="col-md-5 text-center"><%=t('welcome.areas_percent')%></h3>
  </div>
  <div class="row" style="margin-bottom: 20px">
    <h4 class="col-md-2 text-center" style="font-size:4em; color:#ff6600">
      <span class="Count"><%= Volunteer.all_active %></span>
      <script>
        $('.Count').each(function () {
          var $this = $(this);
          jQuery({ Counter: 0 }).animate({ Counter: $this.text() }, {
            duration: 5000,
            easing: 'swing',
            step: function () {
              $this.text(Math.ceil(this.Counter));
            }
          });
        });
      </script>
    </h4>
    <h4 class="col-md-2 text-center" style="font-size:4em; color:#ff6600">
      <span class="counter2"><%= Project.all_active %></span>
        <script>
          $('.counter2').each(function () {
            var $this = $(this);
            jQuery({ Counter: 0 }).animate({ Counter: $this.text() }, {
              duration: 5000,
              easing: 'swing',
              step: function () {
                $this.text(Math.ceil(this.Counter));
              }
            });
          });
        </script>
    </h4>
    <div class="col-md-3">
      <%= pie_chart @participation_projects.map {|pp| [ t("pt_extend.#{pp.subtype_pt.blank? ? 'other' : pp.subtype_pt}"),  pp.total]}, library:{animation:{easing: 'easeOutQuad',duration: 5000}} %>
    </div>
    <div class="col-md-5">
      <%= pie_chart @areas_percent, library:{animation:{easing: 'easeOutQuad',duration: 5000}} %>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<%= javascript_tag do %>
  var locations = <%= raw @locations.to_json %>;
  var project = true;
  var url_map = "<%= Rails.application.secrets.url_map %>";
  var url_rotulacion = "<%= Rails.application.secrets.url_rotulacion %>";
  var list_days = <%= raw @list_days.to_json %>;
  var lock = true;
  var day_c = ""
<% end %>

<script  src="https://www.gstatic.com/charts/loader.js"></script>
<div id="contents_for_welcome">
  <% content_for :title, t('welcome.main_title').html_safe, alt: t('welcome.main_title').html_safe? %>
  <% content_for :description, t('welcome.description').html_safe, alt: t('welcome.description').html_safe? %>
</div>
<div class="section-cont">
  <h2 class="section-name">
  <span class="section-name-title">
    <%=@component_home.try(:title)%>
  </span>
  </h2>
</div>

<%@components.each do |c|%>
  <%= render 'projects', c: c if c.denomination == 'Proyectos destacados'%>
  <%= render 'statistics', c: c if c.denomination == 'Estadísticas de la comunidad'%>
  <%= render 'agends', c: c if c.denomination == 'Agenda de actividades solidarias'%>
  <%= render 'rrss', c: c if c.denomination == 'Redes sociales'%>
  <%= render 'map', c: c if c.denomination == 'Mapa'%>
<%end%>