config/routes.rb
Rails.application.routes.draw do

  get "/", to: redirect("/volun")

  scope "volun" do
    mount Ckeditor::Engine => '/ckeditor'
    concern :downloadable do
      get 'download', on: :member
    end
    resources :new_campaings 

    namespace :rt do
      resources :others, only:[:new,:create]
      resources :activity_unpublishings, only:[:new,:create], param: :activity_id
      resources :activity_publishings, only:[:new,:create]
      resources :project_unpublishings, only:[:new,:create], param: :project_id
      resources :project_publishings, only:[:new,:create], param: :project_id
      resources :volunteers_demands, only:[:new,:create], param: :project_id
      resources :entity_unsubscribes, only:[:new,:create]
      resources :volunteer_appointments, only:[:new,:create]
      resources :volunteer_amendments, only:[:new,:create]
      resources :volunteer_unsubscribes, only:[:new,:create], param: :project_id
      resources :volunteer_subscribes, only:[:new,:create,:index]
      resources :volunteer_project_subscribes, only:[:new,:create,:index]
      resources :solidarity_chains, only:[:new,:create]
    end

    resources :addresses do
      get 'bdc_search_towns', on: :collection
      get 'bdc_search_roads', on: :collection
      get 'bdc_search_road_numbers', on: :collection
    end

    resources :activities, only: [:show, :index ] do
      collection do
        get :my_area
        get :boroughs
        get :search
      end
    end

    resources :entities, only:[:show,:new,:create] do
      resources :projects, only:[:index, :show], param: :q
      resources :activities, only:[:index, :show], param: :q
    end

    resources :projects, only: [:show, :index] do
      collection do
        get :my_area
        get :boroughs
        get :search
      end
      resources :images
      resources :links
    end

    resources :links, concerns: :downloadable

    # resources :volunteers do
    #   resources :projects, only:[:index], param: :q
    # end

    devise_for :users, controllers: {
                        sessions: 'users/sessions',
                        passwords: 'users/passwords',
                        registrations: 'users/registrations'
                      }
    resources :users, only: [:show] do
      collection do
        get :search_activities
        get :search_projects
        get :search_requests
        get :search_meetings
        post :download_zip
      end
    end

    get 'text_json' => 'welcome#test'

    get 'welcome/index'
    get '/whoami' => 'pages#whoami'
    get '/accesibility' => 'pages#accesibility'
    get '/volunteers' => 'pages#volunteers'
    get '/entities' => 'pages#entities'
    get '/mailchimp' => 'pages#mailchimp'
    get '/conditions' => 'pages#conditions'
    get '/blog' => redirect("https://voluntariospormadridblog.madrid.es/")
    get '/mta_privacy' => 'pages#mta_privacy'

    get '/apple-app-site-association', to: redirect('/system/apple-app-site-association')
    get '/.well-known/apple-app-site-association', to: redirect('/system/apple-app-site-association')
    resources :pages, path: '/', only: [:show]

    root 'welcome#index'
    post "/" => "welcome#index"

    draw :ws
    draw :profile
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
  enum kind: {
    pt_social:     1,
    pt_centre:     2,
    pt_permanent:  3,
    pt_punctual:   4,
    pt_entity:     5,
    pt_subvention: 6,
    pt_other:      7
  }

  validates :kind, presence: true

  def self.active?(kind)
    send(kind).take.try(:active?)
  end

  def extendable?
    kind.classify.sub(/\APt/, 'Pt::').safe_constantize.present?
  end
end

app/controllers/profile/projects_controller.rb
class Profile::ProjectsController < ProfileController
  before_action :load_project, except: [:vote_comment_down,:vote_comment_up]
  before_action :load_topic, except: [:show,:faq,:topic,:new_topic,:create_topic]
  before_action :load_comment, only: [:vote_comment_down,:vote_comment_up]
  before_action :permited_faq, only: [:faq]
  before_action :permited_debate, except: [:faq, :show]
  

  def show
  rescue => e
    log_error("COD-00001",e) 
  end

  def faq
    @digital_faqs = @project.digital_faqs.active.order(order: :asc)
  rescue => e
    log_error("COD-00002",e) 
  end

  def topic
    @digital_topics= @project.digital_topics.active

    if !params[:search_text].blank?
      @digital_topics = @digital_topics.where("translate(UPPER(cast(digital_topics.title as varchar)), 'ÁÉÍÓÚ', 'AEIOU') LIKE translate(UPPER(cast(? as varchar)), 'ÁÉÍÓÚ', 'AEIOU') OR translate(UPPER(cast(digital_topics.body as varchar)), 'ÁÉÍÓÚ', 'AEIOU') LIKE translate(UPPER(cast(? as varchar)), 'ÁÉÍÓÚ', 'AEIOU')", "%#{params[:search_text]}%","%#{params[:search_text]}%")
    end
    if !params[:search_type].blank?
      @digital_topics = @digital_topics.where("id #{params[:search_type].to_s == "unfollow" ? "not" : ""} in (?)", Digital::Follow.where(userable: current_user).select(:digital_topic_id))
    end
  rescue => e
    log_error("COD-00003",e)
  end

  def new_topic
    @digital_topic = Digital::Topic.new(project: @project)
  rescue => e
    log_error("COD-00004",e) 
  end

  def create_topic
    @digital_topic = Digital::Topic.new(digital_topic_params)
    @digital_topic.project = @project
    @digital_topic.moderate_status = ModerateStatus.find_by(code: 'pending')

    if @digital_topic.save
      redirect_to topic_digital_path(@project), notice: "Se ha guardado correctamente el foro de debate"
    else
      render :new_topic
    end
  rescue => e
    log_error("COD-00005",e) 
  end

  def vote_topic_up
    exist = Digital::Vote.find_by(userable: current_user, votable: @digital_topic)
    if exist.blank? 
      vote = Digital::Vote.new(userable: current_user, votable: @digital_topic, value: 1)
      if vote.save
        if params[:show].blank?
          redirect_to topic_digital_path(@project), notice: "Has votado el foro de debate"
        else
          redirect_to topic_show_digital_path(@project,vote), notice: "Has votado el foro de debate"
        end
      else
        if params[:show].blank?
          redirect_to topic_digital_path(@project), alert: "No puedes realizar el voto"
        else
          redirect_to topic_show_digital_path(@project,vote), alert: "No puedes realizar el voto"
        end
      end
    elsif exist.value < 0
      exist.value = 1
      if exist.save
        if params[:show].blank?
          redirect_to topic_digital_path(@project), notice: "Has votado el foro de debate"
        else
          redirect_to topic_show_digital_path(@project,exist), notice: "Has votado el foro de debate"
        end
      else
        if params[:show].blank?
          redirect_to topic_digital_path(@project), alert: "No puedes realizar el voto"
        else
          redirect_to topic_show_digital_path(@project,exist), alert: "No puedes realizar el voto"
        end
      end
    else
      if params[:show].blank?
        redirect_to topic_digital_path(@project), alert: "Ya has votado el foro de debate"
      else
        redirect_to topic_show_digital_path(@project,exist), alert: "Ya has votado el foro de debate"
      end
    end
  rescue => e
    log_error("COD-00006",e) 
  end

  def vote_topic_down
    exist = Digital::Vote.find_by(userable: current_user, votable: @digital_topic)
    if exist.blank? 
      vote = Digital::Vote.new(userable: current_user, votable: @digital_topic, value: -1)
      if vote.save
        if params[:show].blank?
          redirect_to topic_digital_path(@project), notice: "Has votado el foro de debate"
        else
          redirect_to topic_show_digital_path(@project,@digital_topic), notice: "Has votado el foro de debate"
        end
      else
        if params[:show].blank?
          redirect_to topic_digital_path(@project), alert: "No puedes realizar el voto"
        else
          redirect_to topic_show_digital_path(@project,@digital_topic), alert: "No puedes realizar el voto"
        end
      end
    elsif exist.value > 0
      exist.value = -1
      if exist.save
        if params[:show].blank?
          redirect_to topic_digital_path(@project), notice: "Has votado el foro de debate"
        else
          redirect_to topic_show_digital_path(@project,@digital_topic), notice: "Has votado el foro de debate"
        end
      else
        if params[:show].blank?
          redirect_to topic_digital_path(@project), alert: "No puedes realizar el voto"
        else
          redirect_to topic_show_digital_path(@project,@digital_topic), alert: "No puedes realizar el voto"
        end
      end
    else
      if params[:show].blank?
        redirect_to topic_digital_path(@project), alert: "Ya has votado el foro de debate"
      else
        redirect_to topic_show_digital_path(@project,@digital_topic), alert: "Ya has votado el foro de debate"
      end
    end
  rescue => e
    log_error("COD-00007",e) 
  end

  def follow_topic_up
    exist = Digital::Follow.find_by(userable: current_user, digital_topic: @digital_topic)
    if exist.blank?
      follow = Digital::Follow.new(userable: current_user, digital_topic: @digital_topic)
      if follow.save
        if params[:show].blank?
          redirect_to topic_digital_path(@project), notice: "Estás siguiendo el foro de debate"
        else
          redirect_to topic_show_digital_path(@project,@digital_topic), notice: "Estás siguiendo el foro de debate"
        end
      else
        if params[:show].blank?
          redirect_to topic_digital_path(@project), alert: "No puedes seguir el debate indicado"
        else
          redirect_to topic_show_digital_path(@project,@digital_topic), alert: "No puedes seguir el debate indicado"
        end
      end
    else
      if params[:show].blank?
        redirect_to topic_digital_path(@project), alert: "Ya sigues el foro de debate"
      else
        redirect_to topic_show_digital_path(@project,@digital_topic), alert: "Ya sigues el foro de debate"
      end
    end
  rescue => e
    log_error("COD-00008",e) 
  end

  def follow_topic_down
    exist = Digital::Follow.find_by(userable: current_user, digital_topic: @digital_topic)
    if !exist.blank?     
      if exist.destroy
        if params[:show].blank?
          redirect_to topic_digital_path(@project), notice: "Has dejado de seguir el foro de debate"
        else
          redirect_to topic_show_digital_path(@project,@digital_topic), notice: "Has dejado de seguir el foro de debate"
        end
      else
        if params[:show].blank?
          redirect_to topic_digital_path(@project), alert: "No puedes dejar de seguir el debate indicado"
        else
          redirect_to topic_show_digital_path(@project,@digital_topic), alert: "No puedes dejar de seguir el debate indicado"
        end
      end
    else
      if params[:show].blank?
        redirect_to topic_digital_path(@project), alert: "Ya has dejado de seguir el foro de debate"
      else
        redirect_to topic_show_digital_path(@project,@digital_topic), alert: "Ya has dejado de seguir el foro de debate"
      end
    end
  rescue => e
    log_error("COD-00009",e) 
  end

  def topic_show
    @digital_comments = @digital_topic.digital_comments.where(digital_comment: nil).active.order(created_at: :desc)
    if !params[:search_text].blank?
      @digital_comments = @digital_comments.where("translate(UPPER(cast(digital_comments.body as varchar)), 'ÁÉÍÓÚ', 'AEIOU') LIKE translate(UPPER(cast(? as varchar)), 'ÁÉÍÓÚ', 'AEIOU')", "%#{params[:search_text]}%")
    end
    @digital_comments= @digital_comments.paginate(page: params[:page], per_page: 20)
  rescue => e
    log_error("COD-00010",e) 
  end

  def create_comment
    @digital_comment = Digital::Comment.new(digital_comment_params)
    @digital_comment.userable = current_user
    @digital_comment.digital_topic = @digital_topic
    @digital_comment.moderate_status = ModerateStatus.find_by(code: 'pending')

    if @digital_comment.save
      redirect_to  topic_show_digital_path(@project,@digital_topic), notice: "Has comentado el debate"
    else
      redirect_to  topic_show_digital_path(@project,@digital_topic), alert: "No se ha podido añadir el comentario al debate"
    end
  rescue => e
    log_error("COD-00011",e) 
  end

  def vote_comment_up
    exist = Digital::Vote.find_by(userable: current_user, votable: @digital_comment)
    if exist.blank? 
      vote = Digital::Vote.new(userable: current_user, votable: @digital_comment, value: 1)
      if vote.save        
        redirect_to topic_show_digital_path(@digital_topic.project,@digital_topic), notice: "Has votado el comentario"
      else       
        redirect_to topic_show_digital_path(@digital_topic.project,@digital_topic), alert: "No puedes realizar el voto"     
      end
    elsif exist.value < 0
      exist.value = 1
      if exist.save        
        redirect_to topic_show_digital_path(@digital_topic.project,@digital_topic), notice: "Has votado el comentario"
      else        
        redirect_to topic_show_digital_path(@digital_topic.project,@digital_topic), alert: "No puedes realizar el voto"
      end
    else
      redirect_to topic_show_digital_path(@digital_topic.project,@digital_topic), alert: "Ya has votado el comentario"      
    end
  rescue => e
    log_error("COD-00012",e) 
  end

  def vote_comment_down
    exist = Digital::Vote.find_by(userable: current_user, votable: @digital_comment)
    if exist.blank? 
      vote = Digital::Vote.new(userable: current_user, votable: @digital_comment, value: -1)
      if vote.save        
        redirect_to topic_show_digital_path(@digital_topic.project,@digital_topic), notice: "Has votado el comentario"

app/views/projects/_albums.html.erb
<%project.albums.order(year: :desc).each do |album|%>
    <div class="well">
        <h4><strong>Album <%=album.year%></strong></h4>
        <p style="margin: 3rem 0rem"><%=album.description.html_safe%></p>
        <%if !album.try(:images).blank?%>
            <div role="tabpanel" class="tab-pane active carousel" id="tpi-tab2">
                <div id="myCarouselAlbum_<%=album&.id%>" class="carousel slide" data-ride="carousel">        
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox" style="height: 70rem">
                        <div class="item active">
                            <%= render partial: "links/link", locals: {link: album.images.first} %>
                        </div>
                        <%= render partial: "links/link", collection: album.images.where("id not in (?)",album.images.first.id) %>
                    </div>
                    <!-- Left and right controls -->
                    <%if  album.images.count > 1 %>
                        <a class="left carousel-control" href="#myCarouselAlbum_<%=album&.id%>" role="button" data-slide="prev">
                            <i class="fa fa-chevron-left" style="background: black" aria-hidden="true"></i>
                            <span class="sr-only"><%=t('action.previous')%></span>
                        </a>
                        <a class="right carousel-control" href="#myCarouselAlbum_<%=album&.id%>" role="button" data-slide="next">
                            <i class="fa fa-chevron-right" style="background: black" aria-hidden="true"></i>
                            <span class="sr-only"><%=t('action.next')%></span>
                        </a>
                    <%end%>
                    <!-- Indicators -->
                    <%if  album.images.count > 1 %>
                        <ol class="carousel-indicators">                
                            <% album.images.each_with_index do |obj,index| %>
                                <%if index==0%>
                                    <li data-target="#myCarouselAlbum_<%=album&.id%>" data-slide-to="0" class="active"></li>
                                <%else%>
                                    <li data-target="#myCarouselAlbum_<%=album&.id%>" data-slide-to="<%=index%>"></li>
                                <%end%>
                            <% end %>
                        </ol>
                    <%end%>
                </div>        
            </div>
        <%end%>
    </div>
<%end%>

app/views/projects/_buscador.html.erb
<style type="text/css">
  .project_search{
    margin: 0px;
  }
</style>
<div class='form form-electronic buscarProyectos'>
  <div class="bg-fluid0">
      <div>
        <div class="panel-heading">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-2"></div>
              <div class="col-md-8">
                <div class="cajaBusqueda" style="margin: 5px 0px;">
                  <div class="row">
                    <div class="col-sm-8">
                      <div class="conjuntoBusqueda">
                        <%= text_field_tag :name_or_description_cont,params[:q][:name_or_description_cont].blank? ? "" : params[:q][:name_or_description_cont],placeholder: t('project.finder.placeholder'), class: "buscarInput", alt: t('project.finder.placeholder'), id: "search_project", 'aria-label' => t('project.finder.placeholder') %>
                        <%= button_tag "",'data-toggle' => 'modal', class: "lupa", value: t('project.finder.find'), alt: t('project.finder.find'), id: t('project.finder.find'), 'aria-label' => t('project.finder.find'),
                          onclick: "submit_form(params_search());"  %>                    
                      </div>
                    </div>
                    <div class="col-sm-4 text-right">
                        <%= button_tag t('project.finder.show_filter'),
                        'data-toggle' => 'collapse',
                        'data-target'=> "#searcher-diary", 
                        class: "panel-title collapsed verFiltros",
                        id: "ver", alt: t('project.finder.show_filter'),
                        onclick: "verOcultar(params_search());",
                         'aria-label' => t('project.finder.find')  %>                  
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-2"></div>
            </div>
          </div>
        </div>
        <div class="panel-body" id="searcher-diary" style="display:none; visibility:hidden;">
          <div class="container-fluid" id="reload_div">
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <div class="form-group date-field">
                    <%= hidden_field_tag :extend_search, 0 %>
                    <label class="labelUp" id="<%=t('project.finder.date_field')%>"><%=t('project.finder.date_field')%></label>
                    <%= text_field_tag :timetables_execution_date_eq,params[:q][:timetables_execution_date_eq] ? "" : params[:q][:timetables_execution_date_eq],:data => {:remote => true}, :class => "form-control small", 
                    id:"search_date", onchange: "submit_form(params_search());"%>
                  </div>
                </div>
                <div class="form-group" >
                  <label class="labelUp" id="<%=t('project.finder.district_field')%>"><%=t('project.finder.district_field')%></label>
                  <%= select_tag :addresses_district_eq, options_for_select(@districts || {}, :selected => params[:q][:addresses_district_eq]), include_blank: true,
                      class: 'big', 
                      style: 'width: 150px; margin:3px 2px;', 
                      id:'search_district',
                      style: 'padding-left: 12px;',
                      onchange: "submit_form(params_search());"%>
                </div>
                <div class="form-group">
                  <label class="labelUp" id="<%=t('project.finder.borough_field')%>"><%=t('project.finder.borough_field')%> </label>
                  
                  <%= select_tag :addresses_borough_eq, options_for_select(@boroughs || {},:selected => params[:q][:addresses_borough_eq]), include_blank: true, 
                    class: 'big', 
                    style: 'width: 150px; margin:3px 2px;', 
                    id:'search_borough',
                    style: 'padding-left: 12px;',
                    onchange: "submit_form(params_search());"%>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <legend class="form-legend"><%=t('project.finder.tematic').html_safe%></legend>
                <% @areas.each do |area| %>
                  <div class="form-group tagW">
                    <label id="<%=area.name%>">
                      <%= check_box_tag "q[areas_name_in][]", area.name, params[:q][:areas_name_in].blank? ? false : (true if params[:q][:areas_name_in].include?(area.name)), onclick: "submit_form(params_search());"%>
                      <span class="tag">
                      <%= area.name.capitalize %></span>
                    </label>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/projects/_numProjects.html.erb
<% if total.to_i > 0 %>
	<h2 class="titlePage"><%= total %> <%= Project.model_name.human(count: total) %></h2>
<% else %>
	<h2 class="titlePage"><%=t('project.not_found')%></h2>
<% end %>

app/views/projects/_order.html.erb
<%= select_tag :order, options_for_select([
                    [t('project.order.default'), ""],
                    [t('project.order.first_new'), "created_at desc"],
                    [t('project.order.first_old'),"created_at asc"],
                    [ t('project.order.relevant'), "projects.order"]],:selected => params[:order]),
                      class: 'selectOrdenar', 
                      'aria-label'=>"selectOrder", 
                      id:'selectOrdenar',
                      onchange: "submit_form(params_search());"%>

app/views/projects/_project.html.erb
<%if !records.blank?%>
<% records.each_slice(3) do |group| %>

<ul class="row">
  <% group.each do |project| %>
  <li class="col-xs-12 col-sm-4 col-md-4" style="display:inline-block">
    <div class="gallery-item" style="padding-bottom:1em">
      <header>
        <style type="text/css">
            .parpadea {
              animation-name: parpadeo;
              animation-duration: 1s;
              animation-timing-function: linear;
              animation-iteration-count: infinite;

              -webkit-animation-name:parpadeo;
              -webkit-animation-duration: 1s;
              -webkit-animation-timing-function: linear;
              -webkit-animation-iteration-count: infinite;
            }
              
              @-moz-keyframes parpadeo{   
                0% { opacity: 1.0; } 
                50% { opacity: 0.5; } 
                100% { opacity: 1.0; } 
              } 
              
              @-webkit-keyframes parpadeo {   
                0% { opacity: 1.0; } 
                50% { opacity: 0.5; } 
                100% { opacity: 1.0; } 
              } 
              
              @keyframes parpadeo {   
                0% { opacity: 1.0; } 
                50% { opacity: 0.5; }
                100% { opacity: 1.0; } 
              }
        </style>
      
        <% if project.urgent %> 
          <p class="parpadea text-left" style="padding:10px; text-transform:uppercase; background: #ff6600; color: white; font-weight: bold; font-size: 20px;"><%=t('project.urgent')%></p> 
        <%end%>
        
      </header>
      <div class="row" style="text-align:center">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <% if  project.logo.try(:path).blank? || project.logo.try(:file).blank?%>
        	<%= image_tag  image_url('missing.png') , class: "logoEspecifico", alt: "missing"  %>
        <% else  %>
        	<%= image_tag  project.logo.try(:path) , class: "logoEspecifico", alt: "#{project.logo.try(:file_file_name).to_s.split(".")[0]}"  %>
        <%end%>
          <%#= render partial: "links/link", collection: project.links.logo %>
        </div>
      </div>
      <div class="main">
        <h3><%= link_to project.name, project_path(project) %></h3>
        <p><%= truncate(strip_tags(project.description), length: 145, :escape => false).html_safe %></p>
        <p><%= project.entity.name %></p>
   
          <p><%= project.execution_start_date%>
            <% unless project.execution_end_date.blank?%> - <%= project.execution_end_date%> 
            <% end %>
          </p>
        <div class="row ctaGroupPreview">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="tags">
              <%= render partial: "shared/area", locals: {areas: project.areas} %>
            </div>
          </div>
          <div class="col-lg-12 text-right">
            <%= link_to  t('action.learn_more') , project_path(project), class: "event-link", alt: t('action.learn_more') %>
          </div>         <br/>
        </div>
      </div>
    </div>
  </li>
    <% end %>
  </ul>
<% end %>
<% end %>

app/views/projects/_show_project.html.erb
<h3 class="summary-title"><%= project&.name&.html_safe %></h3>
<% if !project&.areas.blank? %>
    <div class=" col tags">
        <%= render partial: "shared/area", locals:{ areas:  project.areas } %>
    </div>
<% end %>
<%if !project.try(:links).try(:image).blank? || !project.try(:logo).blank?%>
    <div class="row">
        <div class="col">
        <%= render partial: "commons/wrapper_slides", locals: {object: project} %>
        </div>
    </div>
<%end%>
<div class="row">
    <div class="col">
        <%= project&.description&.html_safe %>
    </div>
</div>
<%= render partial: "projects/subproyects", locals: {project: project}%>
<%= render partial: "commons/links_url_video", locals: {resource: project}%>
<%= render partial: "projects/albums", locals: {project: project}%>

app/views/projects/_subproyects.html.erb
<%if !project.subtype_proyect.blank?%>
    <div style="margin-top: 5rem">
        <%if project.subtype_proyect == "subproyect"%>
            <div class="row well">
                <%= content_tag :h2, "Proyecto Matriz", class: 'form-subtitle' %>
            
                <div class="col" style="width:100%;overflow-x:auto;">
                    <table class="index-table" >
                        <thead>
                        <tr>
                            <% Project.matriz_columns.each do |column| %>
                                <th><%=Project.human_attribute_name(column) %></th>
                            <% end %>
                        </tr>
                        </thead>            
                        <tbody>
                            <tr>
                                <% Project.matriz_columns.each do |column| %>
                                    <td><%= project.father.try(column.to_sym).blank? ? "" : (link_to project.father.try(column.to_sym), project_path(project.father))  %></td>
                                <% end %>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        <%elsif !project.subprojects.blank?%>
            <div class="row well">
                <%= content_tag :h2, "Subproyectos", class: 'form-subtitle' %>
            
                <div class="col" style="width:100%;overflow-x:auto;">
                    <table class="index-table" >
                        <thead>
                            <tr>
                                <% Project.subproyect_columns.each do |column| %>
                                    <th><%=Project.human_attribute_name(column) %></th>
                                <% end %>      
                            </tr>
                        </thead>            
                        <tbody>
                            <% project.subprojects.order(:pt_order).each do |sub|  %>
                                <tr>                               
                                    <% Project.subproyect_columns.each do |column| %>
                                        <td><%= sub.try(column.to_sym).blank? ? "" : (link_to sub.try(column.to_sym), project_path(sub))  %></td>
                                    <% end %>                              
                                </tr>
                            <%end%>
                        </tbody>
                    </table>
                </div>
            </div>
        <%end%>
    </div>
<%end%>

app/views/projects/_total_projects.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="tags">
      <% if params[:per_page].to_i != records.count.to_i%>
        <%=link_to t('project.show_all'), projects_path(per_page: records.count), {class: "event-link",onclick: "search_clear_project()" }%> 
      <%end%>
    </div>
  </div>
</div>

app/views/projects/_volunteers_allowed.html.erb
<% if @project.volunteers_allowed %>
    <% if current_user && current_user.loggable_type=="Volunteer" %>
        <%if @project.volunteers.where("projects_volunteers.volunteer_id = ? and projects_volunteers.project_id = ?", current_user.loggable_id, @project.id ).exists? %>
            <div class="ctaVoluntarios">
            <h3><%= t('project.subscribed') %></h3>
            </div>
        <% elsif (Rt::VolunteerSubscribe.includes(:request_form).where("project_id= ? and request_forms.user_id=?", @project.id, current_user.id ).references(:request_form).exists? || Rt::VolunteerProjectSubscribe.includes(:request_form).where("project_id= ? and request_forms.user_id=?", @project.id, current_user.id ).references(:request_form).exists?)   %>
            <div class="ctaVoluntarios">
            <h3><%= t('project.requested') %></h3>
            </div>
        <% else  %>
            <div class="ctaVoluntarios">
            <h3><%= t('project.need_volunteers') %></h3>
            <% if current_user.blank? %>
                <%= link_to t('project.interesting') , new_rt_volunteer_subscribe_path(project_id: @project.id), class: "event-link big", alt: t('project.interesting') %>
            <% else %>
                <%= link_to t('project.interesting') , new_rt_volunteer_project_subscribe_path(project_id: @project.id), class: "event-link big", alt: t('project.interesting') %>
            <% end %>
            </div>
        <% end %>
    <% end %>
<% end %>
<br>

app/views/projects/show.html.erb
<div class="container-fluid single actividadSingle">
  <%=render partial: "commons/back_show_list", locals: {path: projects_path, text: t('application.projects')}%>

  <div class="row">
    <div class="col-md-8">
      <%=render partial: "projects/show_project", locals: {project: @project}%>
    </div>
    <div class="col-md-4">
      <%= render partial: "commons/sidebar_projects", member: @project %>
    </div>
  </div>
  <div class="row" style="margin-top: 5rem">      
    <div class="col-md-8">        
      <%= render partial: "commons/share_links", locals: {object: @project} %>    
    </div>
  </div>
</div>

app/views/projects/show.js.erb
  var locations = <%= raw @locations.to_json %>;
  var multiple = true;
  var url_map = "<%= Rails.application.secrets.url_map %>";
  var url_rotulacion = "<%= Rails.application.secrets.url_rotulacion %>";
  load_map();
  $('#timetables').html('<%= escape_javascript(render partial: 'timetables/timetables_by_date_project', locals: {events: @timetables, day:@day}) %>');