config/routes.rb
Rails.application.routes.draw do

  get "/", to: redirect("/volun")

  scope "volun" do
    mount Ckeditor::Engine => '/ckeditor'
    concern :downloadable do
      get 'download', on: :member
    end
    resources :new_campaings 

    namespace :rt do
      resources :others, only:[:new,:create]
      resources :activity_unpublishings, only:[:new,:create], param: :activity_id
      resources :activity_publishings, only:[:new,:create]
      resources :project_unpublishings, only:[:new,:create], param: :project_id
      resources :project_publishings, only:[:new,:create], param: :project_id
      resources :volunteers_demands, only:[:new,:create], param: :project_id
      resources :entity_unsubscribes, only:[:new,:create]
      resources :volunteer_appointments, only:[:new,:create]
      resources :volunteer_amendments, only:[:new,:create]
      resources :volunteer_unsubscribes, only:[:new,:create], param: :project_id
      resources :volunteer_subscribes, only:[:new,:create,:index]
      resources :volunteer_project_subscribes, only:[:new,:create,:index]
      resources :solidarity_chains, only:[:new,:create]
    end

    resources :addresses do
      get 'bdc_search_towns', on: :collection
      get 'bdc_search_roads', on: :collection
      get 'bdc_search_road_numbers', on: :collection
    end

    resources :activities, only: [:show, :index ] do
      collection do
        get :my_area
        get :boroughs
        get :search
      end
    end

    resources :entities, only:[:show,:new,:create] do
      resources :projects, only:[:index, :show], param: :q
      resources :activities, only:[:index, :show], param: :q
    end

    resources :projects, only: [:show, :index] do
      collection do
        get :my_area
        get :boroughs
        get :search
      end
      resources :images
      resources :links
    end

    resources :links, concerns: :downloadable

    # resources :volunteers do
    #   resources :projects, only:[:index], param: :q
    # end

    devise_for :users, controllers: {
                        sessions: 'users/sessions',
                        passwords: 'users/passwords',
                        registrations: 'users/registrations'
                      }
    resources :users, only: [:show] do
      collection do
        get :search_activities
        get :search_projects
        get :search_requests
        get :search_meetings
        post :download_zip
      end
    end

    get 'text_json' => 'welcome#test'

    get 'welcome/index'
    get '/whoami' => 'pages#whoami'
    get '/accesibility' => 'pages#accesibility'
    get '/volunteers' => 'pages#volunteers'
    get '/entities' => 'pages#entities'
    get '/mailchimp' => 'pages#mailchimp'
    get '/conditions' => 'pages#conditions'
    get '/blog' => redirect("https://voluntariospormadridblog.madrid.es/")
    get '/mta_privacy' => 'pages#mta_privacy'

    get '/apple-app-site-association', to: redirect('/system/apple-app-site-association')
    get '/.well-known/apple-app-site-association', to: redirect('/system/apple-app-site-association')
    resources :pages, path: '/', only: [:show]

    root 'welcome#index'
    post "/" => "welcome#index"

    draw :ws
    draw :profile
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  
  belongs_to :project
  belongs_to :entity

  has_many :events, class_name: "Event", foreign_key: 'eventable_id', as: :eventable
  has_many :links, class_name: "Link", foreign_key: 'linkable_id', as: :linkable
  has_many :timetables, through: :events
  has_many :addresses, through: :events
  
  has_and_belongs_to_many :areas_activities, optional: true
  has_and_belongs_to_many :areas, ->{ where(active: true).order('areas.name asc') }, :through => :areas_activities
  has_many :images, -> { activity_images }, class_name: 'Link', foreign_key: 'linkable_id'
  has_many :videos, -> { activity_videos }, class_name: 'Link', foreign_key: 'linkable_id'
  has_many :docs,   -> { activity_docs   }, class_name: 'Link', foreign_key: 'linkable_id'
  has_many :urls,   -> { activity_urls   }, class_name: 'Link', foreign_key: 'linkable_id'
  has_one  :logo,   -> { activity_logo   }, class_name: 'Link', foreign_key: 'linkable_id', required: false, validate: false


  accepts_nested_attributes_for :events
  accepts_nested_attributes_for :links
  accepts_nested_attributes_for :videos, reject_if:  :all_blank, allow_destroy: true
  accepts_nested_attributes_for :docs,   reject_if:  :all_blank, allow_destroy: true
  accepts_nested_attributes_for :urls,   reject_if:  :all_blank, allow_destroy: true
  accepts_nested_attributes_for :logo,   reject_if:  :all_blank, allow_destroy: true

  default_scope { where(publish: true, active: true) }
  scope :activities_present, (->(day) { where("timetables.execution_date >= ? and events.eventable_type='Activity'", day) })

  def to_s
    name
  end

  def self.ransack_default
    { s: 'id desc' }
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!, only: :my_area
  before_action :load_query_search, only: :search
  before_action :set_activity, only: :show
  before_action :set_list_days_show, only: :show
  before_action :set_locations, only: :show
  before_action :set_areas, only: :index
  before_action :set_districts, only: :index
  before_action :set_boroughs, only: :index
  before_action :set_list_days, only: :index
  before_action :load_query, only: :index
  before_action :search_complete, only: [:index,:search]

  before_action :load_data_calendar, only: [:index, :show]
  respond_to :html, :js, :json

  def my_area
    params[:q] ||= Activity.ransack_default
    @search_q = Activity.all
    @activities = @search_q.result.page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  rescue => e
    begin
      Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def index
    Ahoy::Event.create(name: "Visit", properties: {title: "Actividades"}.to_json, user_id: current_user.try(:id), visit_id: current_visit.try(:id), time:Time.now)
    @activities_search = @activities_unpag
    
    if !params[:search_text].to_s.strip.blank?
      @activities_search = @activities_search.where("TRANSLATE(UPPER(name),'ÁÉÍÓÚ','AEIOU') LIKE TRANSLATE(UPPER(?),'ÁÉÍÓÚ','AEIOU') OR TRANSLATE(UPPER(description),'ÁÉÍÓÚ','AEIOU') LIKE TRANSLATE(UPPER(?),'ÁÉÍÓÚ','AEIOU')","%#{params[:search_text]}%","%#{params[:search_text]}%")
    end

    if !params[:search_district].to_s.strip.blank?
      @activities_search = @activities_search.where("id in (?)",Activity.joins(:addresses).where("addresses.district_id = ?", params[:search_district]).select(:id))
    end

    if !params[:search_borought].to_s.strip.blank?
      @activities_search = @activities_search.where("id in (?)",Activity.joins(:addresses).where("addresses.borought_id = ?", params[:search_borought]).select(:id))
    end
    
    if !params[:search_areas].blank?     
      @activities_search = @activities_search.where("id in (?)", Activity.joins(:areas).where("areas.id in (?)",params[:search_areas].to_s.gsub(/\"|\[|\]/,'').strip.split(',')).select(:id))
    end

    if !params[:select_check].blank? && params[:select_check].to_s=='day'
      @activities_search = @activities_search.where(" cast(? as date) =cast(start_date as date) OR cast(? as date) = cast(end_date as date) OR  cast(? as date) between cast(start_date as date) and cast(end_date as date)",@current_date_calendar,@current_date_calendar, @current_date_calendar)
    else
      start_date =  @current_date_calendar.beginning_of_month.to_date
      end_date=  @current_date_calendar.end_of_month.to_date
      @activities_search = @activities_search.where("start_date::date between ?::date and ?::date OR end_date::date between ?::date and ?::date OR ?::date between start_date::date and end_date::date OR ?::date between start_date::date and end_date::date ",start_date,end_date,start_date,end_date, start_date,end_date ) 
    end


    @num_records = @activities_search.count
  
    @activities = @activities_search.paginate(page: params[:page], per_page: Kaminari.config.default_per_page)
    respond_to do |format|
      format.html
      format.js { render action: 'search.js.erb' }
    end
  rescue => e
    begin
      Rails.logger.error("COD-00002: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def search
    respond_to do |format|
      format.js
    end
  rescue => e
    begin
      Rails.logger.error("COD-00003: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def boroughs
    @boroughs = Activity.includes(:addresses).distinct.where('addresses.district=?', params[:district]).order('addresses.borough').pluck('addresses.borough', 'addresses.borough')
    respond_to do |format|
      format.json { render json: @boroughs }
    end
  rescue => e
    begin
      Rails.logger.error("COD-00004: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def show
   
    @timetables = @activity.timetables.where(timetables: { execution_date: params[:day] })
    @day = params[:day].to_json
    respond_to do |format|
      format.html
      format.js
    end
  rescue => e
    begin
      Rails.logger.error("COD-00005: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  protected

    def search_complete
      timetables_aux = @search_q.result

      @num_records = timetables_aux.length
      @timetables = timetables_aux.paginate(page: params[:page], per_page: Kaminari.config.default_per_page)
    end

    def load_query
      if params[:day]
        @search_q = Timetable.select('execution_date,activities.id, activities.name').joins(:activity).group('execution_date, activities.id').search(execution_date_eq: params[:day])
        @day = params[:day]
      else
        @search_q = Timetable.select('execution_date, activities.id').joins(:activity).order(:execution_date).group('execution_date, activities.id').search(execution_date_gteq: Time.now)
        @day = nil
      end
    end

    def load_query_search
      if params[:day]
        @day = params[:day]
        @search_q = Timetable.select('execution_date, activities.id, activities.name').joins(:activity).order(:execution_date).group('execution_date, activities.id').search(execution_date_eq: @day)
      else
        @day = nil
        @search_q = Timetable.select('execution_date, activities.id, activities.name').joins(:activity).order(:execution_date).group('execution_date, activities.id').search(params[:q])
      end
    end

    def set_list_days_show
      @list_days_activity = @activity.timetables.pluck('timetables.execution_date').to_json
    end

    def set_list_days
      @list_days = Activity.includes(:timetables).distinct.activities_present(Time.now).order('timetables.execution_date').pluck('timetables.execution_date').to_json
    end

    def set_locations
      params[:day] ||= @activity.timetables.minimum(:execution_date).try :strftime, '%Y-%m-%d'
      @locations = Event.includes(:address, :activity, :timetables).where(activities: { id: params[:id] }, timetables: { execution_date: params[:day] }).as_json(only: [:id], include: { address: { only: [:latitude, :longitude] } })
    end

    def set_boroughs
      @boroughts = Borought.where("id in (?)",  Activity.joins(:addresses).select(:borought_id))    
    end

    def set_areas
      @areas = Area.all.order(:name)
    end

    def set_districts
      @districts = District.where("id in (?)",  Activity.joins(:addresses).select(:district_id))
    end

    def set_activity
      @activity = Activity.find(params[:id])
    rescue
      redirect_to activities_path, alert: "No existe la actividad"
    end

    def activity_params
      params.require(:activity).permit(:name, :description, :active)
    end

    def allow_iframe
      response.headers.delete 'X-Frame-Options'
    end

  private

  def load_data_calendar
    @current_date_calendar ||= Date.today   
    if !params[:set_date].blank?
      begin
        @current_date_calendar = Date.parse(params[:set_date])    
      rescue
        convert_date=params[:set_date].split('-')
        begin
          params[:set_date]="#{convert_date[0]}-#{convert_date[1]}-1"
          @current_date_calendar = Date.parse("#{convert_date[0]}-#{convert_date[1]}-1")  
        rescue
          @current_date_calendar=Date.today
        end
      end
    end

    start_date =  @current_date_calendar.beginning_of_month.to_date
    end_date=  @current_date_calendar.end_of_month.to_date
    @activities_unpag = Activity.all.order(start_date: :desc).where("start_date::date between ?::date and ?::date OR end_date::date between ?::date and ?::date OR ?::date between start_date::date and end_date::date OR ?::date between start_date::date and end_date::date ",start_date,end_date,start_date,end_date, start_date,end_date ) 
  end
end

app/views/activities/_activity.html.erb
<div class="actividadWrapper">
  <div class="row">
    <div class="col-sm-4 col-xs-4  no-padding-left" style="border-right: 0.3rem solid">
      <div class="row">
        <div class="<%= !activity.end_date.blank? ? "col-sm-6" : "col" %> fecha">
          <%= activity.start_date.day %>
          <span><%= MONTHNAMES[activity.start_date.month] %> <%= activity.start_date.year %></span>
        </div>
        <%if !activity.end_date.blank?%>
          <div class="col-sm-6  fecha">
            <%= activity.end_date.day %>
            <span><%= MONTHNAMES[activity.end_date.month] %> <%= activity.end_date.year %></span>
          </div>  
        <%end%>  
      </div>
    </div>
    <div class="col-sm-8 col-xs-8">
      <p class="distrito">
        <% activity.addresses.select(:district_id).distinct.each do |address| %>
          <p class="distrito"><%= address.district %></p>
        <% end %>
      </p>
      <h3 class="titular"><%=activity.try(:name) %></h3>
      <p><%=activity.try(:description).to_s.truncate(75,omission: '...').html_safe %><p>
    </div>
    <i><%= link_to  " " , activity_path(activity.id), class: "fa fa-chevron-right" %> </i>
  </div>
</div>

app/views/activities/_buscador.html.erb
<div id="buscarAtividades" class="form form-electronic panel-body" style="background-color: rgba(29, 29, 29, 0.05);padding: 3rem ">
<%= form_tag activities_path, :method => :get, class: "dates_form" do |f| %>
  <%= hidden_field_tag :set_date, params[:set_date] %>
  <div class="row">
    <div class="col-sm-4 calendar_columns " style="padding: 1rem">
        <%=label_tag :select_day, "Día", class: "labelUp" %>
        <%= select_day(@current_date_calendar,{prefix: :select},{class: "calendar_select",onchange: "send_form()"})%>
    </div>
    <div class="col-sm-4  calendar_columns"  style="padding: 1rem">
        <%=label_tag :select_month, "Mes", class: "labelUp" %>
        <%= select_month(@current_date_calendar,{prefix: :select},{class: "calendar_select",onchange: 'send_form()'})%>
    </div>
    <div class="col-sm-4   calendar_columns"  style="padding: 1rem">
        <%=label_tag :select_year, "Año", class: "labelUp" %>
        <%= select_year(@current_date_calendar, {prefix: :select,start_year: 2005},{class: "calendar_select",onchange: 'send_form()'})%>
    </div>         
  </div>   
  <div class="row">
    <div class="col-sm-2 calendar_columns text-center">
      <%=link_to "<i class='fa fa-angle-double-left fa-2x'></i>".html_safe,set_init_month_calendar(params), class: "event-link", style: "padding: 0.5rem 2rem"%>
    </div>
    <div class="col-sm-2  calendar_columns text-center" >
      <%=link_to "<i class='fa fa-angle-left fa-2x'></i>".html_safe,set_previus_month_calendar(params), class: "event-link", style: "padding: 0.5rem 2rem"%>
    </div>
    <div class="col-sm-4   calendar_columns text-center" >
      <%=link_to "Hoy",set_now_calendar(params), class: "event-link"%>
    </div>
    <div class="col-sm-2 calendar_columns text-center">
      <%=link_to "<i class='fa fa-angle-right fa-2x'></i>".html_safe,set_next_month_calendar(params), class: "event-link", style: "padding: 0.5rem 2rem"%>
    </div>
    <div class="col-sm-2  calendar_columns text-center">
      <%=link_to "<i class='fa fa-angle-double-right fa-2x'></i>".html_safe,set_finish_month_calendar(params), class: "event-link", style: "padding: 0.5rem 2rem"%>
    </div>
  </div>
  <div class="row" style="padding: 0px;overflow-x:auto;">   
    <table class="table table-striped" style="width: 100%;margin-top: 1rem">
      <thead><tr><%=get_week_first_monday%></tr></thead>
      <tbody><%=get_days_month_range(@current_date_calendar, @activities_unpag, params)%></tbody>
    </table>
  </div>
  <div class="row" style="margin-bottom: 3rem">    
    <div class="col-sm-6   calendar_columns text-center" >
      <%=link_to "Día",set_day_calendar(params), class: params[:select_check].to_s == 'day' ? "event-link" : "secondary-link"%>
    </div>
   <div class="col-sm-6   calendar_columns text-center" >
      <%=link_to "Mes",set_month_calendar(params), class: params[:select_check].blank? || params[:select_check].to_s == 'month' ? "event-link" : "secondary-link"%>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div style="height: 1rem;width: 1rem; border-radius: 100%;background: rgba(255, 102, 0, 1);float: left;padding: 0.8rem;margin-right: 1rem;"></div> Eventos
    </div>
    <div class="col-12">
      <div style="height: 1rem;width: 1rem; border-radius: 100%;background: #FFA200;float: left;padding: 0.8rem;margin-right: 1rem;"></div> Día actual
    </div>
  </div>
  <div class="row" style="padding-top: 5rem">
    <div class="col calendar_columns">
      <%=label_tag :search_text, "#{t('activity.filter.description')} <span class='asterisco'>*</span>".html_safe, class: "labelUp" %>
      <%= text_field_tag :search_text,params[:search_text], class: "calendar_input", placeholder: t('activity.filter.find_placeholder'), 'aria-label' => t('activity.filter.find_placeholder') %>          
    </div>
  </div>
  
  <div class="row"  style="padding-top: 2rem">
    <div class="col calendar_columns">
      <%=label_tag :search_district, t('activity.filter.district'), class: "labelUp" %>
      <%= select_tag :search_district, options_from_collection_for_select(get_districts,"id","name", params[:search_district]), include_blank: '',class: "calendar_select" %>  
    </div>
  </div>
  <div id="boroughts">
  <div class="row"  style="padding-top: 2rem">
    <div  class="col calendar_columns">
      <%=label_tag :search_borought, t('activity.filter.borough'), class: "labelUp" %>
      <%= select_tag :search_borought, options_from_collection_for_select(get_boroughts(params[:search_district]),"id","name",  params[:search_borought]),include_blank: '', class: "calendar_select" %>
    </div>
  </div>
 
  </div>
  <div class="row"  style="padding-top: 2rem">
    <div class="col calendar_columns">
      <%=label_tag "search_areas[]", t('activity.filter.tematic').html_safe, class: "labelUp" %>
      <div class="row" style="padding: 2rem">
        <% @areas.each do |area| %>
          <div style="float:left">
            <label alt="<%= area.name %>">
              <%= check_box_tag "search_areas[]", area.id,!params[:search_areas].blank? && params[:search_areas].include?(area.id.to_s)  %>
              <span class="tag"><%= area.name.capitalize %></span>
            </label>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col calendar_columns">
      <div class="button-group text-right mt20">
        <%= submit_tag t('activity.action.find'), class: "event-link", alt: t('activity.action.find')%>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/activities/_numActivities.html.erb
<h4 class="numActividades">
    <span><%= events %></span>
    <%= Activity.model_name.human(count: events) %>
</h4>

app/views/activities/index.html.erb
<% content_for :title, t('activity.main_title').html_safe  %>
<% content_for :description, t('activity.description').html_safe %>

<div class="container-fluid">
  <h1 class="titlePage" alt="<%=t('activity.title')%>"><%=t('activity.title')%></h1>
  <div class="row">
    <div class="col-md-4">      
      <%= render "buscador" %>
    </div>
    <div class="col-md-8">
      <div class="row">
        <%= render partial: 'numActivities', locals: {events: @activities_search.count}  %>
      </div>
      <div class="row" style="overflow: auto;height: 112rem;">
        <% @activities.each do |activity|%>
          <div class="col-12">
            <%=render 'activity', activity: activity%>
          </div>
        <%end%>
      </div>      
      <div class ="row">
        <div class="col">
          <%= render partial: "shared/pagination", locals: {collection: @activities} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/search.js.erb
<% if @timetables.current_page > 1 %>
  $('#activities').append('<%= escape_javascript(render partial: 'timetables/timetable', collection: @timetables)  %>');
<% else %>
  $('#numActividades').html ('<%= escape_javascript(render partial: 'numActivities', locals: {events: @num_records}) %>')
  $('#activities').html('<%= escape_javascript(render partial: 'timetables/timetable', collection: @timetables) %>');
<% end %>
$('#scroll_activities').html('<%= escape_javascript(render partial: 'shared/scroll_infinite_activities', locals: {records: @timetables, num_records: @num_records}) %>');

app/views/activities/show.html.erb
<div class="container-fluid single actividadSingle">
  <%=render partial: "commons/back_show_list", locals: {path: activities_path, text: t('application.activities')}%>

  <div class="row">    
    <div class="col-md-8">
      <h3 class="summary-title"><%= @activity&.name %></h3>
      <div class="row">
        <% if !@activity&.areas.blank? %>
          <div class=" col tags">
            <%= render partial: "shared/area", locals:{ areas:  @activity.areas } %>
          </div>
        <% end %>
      </div>
      <%if !@activity.try(:links).try(:image).blank? || !@activity.try(:logo).blank?%>
        <div class="row">
          <div class="col">
            <%= render partial: "commons/wrapper_slides", locals: {object: @activity} %>
          </div>
        </div>
      <%end%>
      <div class="row">
        <div class="col">
           <%= @activity&.description&.html_safe %>
        </div>
      </div>
      <%= render partial: "commons/links_url_video", locals: {resource: @activity}%>      
      <div class="bg-fluid5 nofluid" style= "margin:20px 0px;">
        <%= link_to t('url_link_activities'), @activity.link_url unless @activity.link_url.blank? %>
      </div> 
      <%if !@activity&.project.blank?%>
        <h4><strong>Datos proyecto asociado</strong></h4>
        <div style="border: 0.3rem solid lightgrey; padding: 3rem; margin-top: 3rem; border-radius: 1rem;margin-bottom: 2rem">
          <%=render partial: "projects/show_project", locals: {project: @activity.project} %>
        </div>
      <%end%>
    </div>
    <div class="col-md-4 ">
      <%= render partial: "commons/sidebar_activities", member: @activity %>
    </div>
  </div>
  <%if @activity.share%>
    <div class="row" style="margin-top: 5rem">    
      <div class="col-md-8">        
        <%= render partial: "commons/share_links", locals: {object: @activity} %>    
      </div>
    </div>
  <%end%>
</div>

app/views/activities/show.js.erb
  var locations = <%= raw @locations.to_json %>;
  var multiple = true;
  var url_map = "<%= Rails.application.secrets.url_map %>";
  var url_rotulacion = "<%= Rails.application.secrets.url_rotulacion %>";
  load_map();
  $('#timetables_by_date').html('<%= escape_javascript(render partial: 'timetables/timetables_by_date_activity', locals: {events: @timetables, day:@day}) %>');